services:
  db:
    image: postgres:17-alpine
    container_name: movie_db
    environment:
      POSTGRES_DB: movie_night_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie_server
    depends_on:
      - db
    ports:
      - "4000:4000"
      - "9229:9229"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: movie_night_db
      DATABASE_USER: movie_user
      DATABASE_PASSWORD: password123
    volumes:
      - ./backend:/usr/src/app
    command: npm run start
    # command: node --inspect=0.0.0.0:9229 ./dist/src/index.js

volumes:
  db-data: