name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branchers:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node.js
      with:
        node-version: '14'

     - name: Install Frontend Dependencies
       working-directory: frontend
       run: npm install

     - name: Run Frontend tests
       working-directory: frontend
       run: npm test -- --watchAll=false

     - name: Build Frontend
       working-directory: frontend
       run: npm run build

     - name: Install Backend Dependencies
       working-directory: backend
       run: npm install

     - name: Run Backend Tests
       working-directory: backend
       run: npm test

     - name: SonarCloud Scan
       uses: SonarSource/sonarcloud-github-action@master
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}	
